### ISSUE TITLE
unable to update gist

### ISSUE THREAD

**Issue by Olvi73** [tobimori/typeracer-box#4]
find this in workflows
```
Run ./
  env:
    GH_TOKEN: ***
    GIST_ID: ***
    TR_USERNAME: ***
Unable to update gist
TypeError: Cannot read property 'content' of undefined
```
